---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by aj.
--- DateTime: 5/11/25 10:26 AM
---
i = Get_Value();

function Run()
    
    return fib(120);
end

function fib(n)
    
    i = i + 1;
    
    print("fib called " .. i .. " times.");
    
    if (n == 0 or n == 1) then
        return 1;
    else
        return fib(n - 1) + fib(n - 2);
    end
end