<Project Sdk="Godot.NET.Sdk/4.4.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" Version="3.6.0" />
    <PackageReference Include="Godot.Logging" Version="1.2.0" />
  </ItemGroup>
</Project>