<Project Sdk="Godot.NET.Sdk/4.4.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" Version="3.6.0" />
    <PackageReference Include="Godot.Logging" Version="1.2.0" />
    <PackageReference Include="morelinq" Version="4.4.0" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Misc\ExampleFiles\Map.lnmap" />
    <Content Include="Misc\ExampleFiles\Map2.lnmap" />
  </ItemGroup>
</Project>